create_db = 'CREATE DATABASE IF NOT EXISTS %s;'

create_pz_01 = """CREATE TABLE  IF NOT EXISTS `PRICE_ZONE_01` (
    `SUPC` VARCHAR(9) NOT NULL,
    `PRICE_ZONE` TINYINT(1) UNSIGNED NOT NULL,
    `CUSTOMER_ID` VARCHAR(14) NOT NULL,
    `EFFECTIVE_DATE` DATETIME NOT NULL,
    PRIMARY KEY (`CUSTOMER_ID`, `SUPC`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;"""

create_pz_02 = """CREATE TABLE  IF NOT EXISTS `PRICE_ZONE_02` (
    `SUPC` VARCHAR(9) NOT NULL,
    `PRICE_ZONE` TINYINT(1) UNSIGNED NOT NULL,
    `CUSTOMER_ID` VARCHAR(14) NOT NULL,
    `EFFECTIVE_DATE` DATETIME NOT NULL,
    PRIMARY KEY (`CUSTOMER_ID`, `SUPC`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;"""

create_pz_03 = """CREATE TABLE  IF NOT EXISTS `PRICE_ZONE_03` (
    `SUPC` VARCHAR(9) NOT NULL,
    `PRICE_ZONE` TINYINT(1) UNSIGNED NOT NULL,
    `CUSTOMER_ID` VARCHAR(14) NOT NULL,
    `EFFECTIVE_DATE` DATETIME NOT NULL,
    PRIMARY KEY (`CUSTOMER_ID`, `SUPC`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;"""

create_pa = """CREATE TABLE  IF NOT EXISTS `PA` (
    `SUPC` VARCHAR(9) NOT NULL,
    `PRICE_ZONE` TINYINT(1) UNSIGNED NOT NULL,
    `PRICE` DOUBLE(13 , 3) NOT NULL,
    `EFFECTIVE_DATE` DATETIME NOT NULL,
    `EXPORTED_DATE` BIGINT(10) UNSIGNED NOT NULL,
    `SPLIT_INDICATOR` CHAR(1) NOT NULL,
    PRIMARY KEY (`SUPC`,`PRICE_ZONE`,`EFFECTIVE_DATE`, `EXPORTED_DATE`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
"""

tables = [create_pz_01, create_pz_02, create_pz_03, create_pa]
